#!/usr/bin/env bash
set -euo pipefail

PLATFORM="${1:-}"

usage() {
  cat >&2 <<USAGE
Usage: $0 <kirkwood|mvebu>

Build a Debian 13 base rootfs tarball for the selected platform.
This script does not install a kernel and never writes to block devices.

Recommended host:
  - Debian 13 amd64
  - root privileges
  - debootstrap and arch-test
  - ARM execution support through binfmt_misc/QEMU
  - bzip2, tar, sha256sum
USAGE
  exit 2
}

[[ -n "$PLATFORM" ]] || usage
case "$PLATFORM" in
  kirkwood|mvebu) ;;
  *) echo "ERROR: unsupported platform: $PLATFORM" >&2; usage ;;
esac

if [[ "${EUID:-$(id -u)}" -ne 0 ]]; then
  echo "ERROR: build-rootfs.sh must run as root." >&2
  exit 3
fi

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
CONFIG_FILE="$REPO_ROOT/rootfs/$PLATFORM/debian-13.env"

[[ -f "$CONFIG_FILE" ]] || {
  echo "ERROR: missing rootfs build definition: $CONFIG_FILE" >&2
  exit 3
}

# shellcheck disable=SC1090
source "$CONFIG_FILE"

for variable in DEBIAN_ARCH DEBIAN_MAJOR DEBIAN_MIRROR DEBIAN_SUITE \
                FSTAB_ROOT_TYPE ROOTFS_HOSTNAME; do
  [[ -n "${!variable:-}" ]] || {
    echo "ERROR: $variable missing from $CONFIG_FILE" >&2
    exit 3
  }
done

for command in debootstrap arch-test chroot tar bzip2 sha256sum awk grep sed sort; do
  command -v "$command" >/dev/null 2>&1 || {
    echo "ERROR: required command not found: $command" >&2
    exit 4
  }
done

arch_test_rc=0
arch-test "$DEBIAN_ARCH" >/dev/null 2>&1 || arch_test_rc=$?
if (( arch_test_rc != 0 )); then
  echo "ERROR: this host cannot execute Debian $DEBIAN_ARCH binaries." >&2
  echo "Enable ARM binfmt_misc/QEMU support before building." >&2
  exit 4
fi

WORK_ROOT="$REPO_ROOT/.work/rootfs-$PLATFORM-debian-$DEBIAN_MAJOR"
ROOTFS_DIR="$WORK_ROOT/rootfs"
OUTPUT_DIR="$REPO_ROOT/dist/rootfs/$PLATFORM/debian-$DEBIAN_MAJOR"
ARCHIVE_NAME="Debian-${DEBIAN_MAJOR}-${PLATFORM}-${DEBIAN_ARCH}-rootfs.tar.bz2"
ARCHIVE_PATH="$OUTPUT_DIR/$ARCHIVE_NAME"
PACKAGE_MANIFEST="$OUTPUT_DIR/PACKAGE-MANIFEST.txt"
METADATA_FILE="$OUTPUT_DIR/ROOTFS-METADATA.txt"

rm -rf "$WORK_ROOT" "$OUTPUT_DIR"
mkdir -p "$ROOTFS_DIR" "$OUTPUT_DIR"

BASE_PACKAGES=(
  ca-certificates
  cron
  e2fsprogs
  ethtool
  ifupdown
  initramfs-tools
  iproute2
  iputils-ping
  isc-dhcp-client
  kmod
  locales
  logrotate
  net-tools
  netbase
  openssh-server
  orphan-sysvinit-scripts
  procps
  rsync
  rsyslog
  sysv-rc
  sysvinit-core
  sysvinit-utils
  systemd-standalone-sysusers
  tzdata
  u-boot-tools
  udev
  wget
)
INCLUDE_PACKAGES="$(IFS=,; echo "${BASE_PACKAGES[*]}")"

export DEBIAN_FRONTEND=noninteractive

echo "==> Bootstrapping Debian $DEBIAN_MAJOR ($DEBIAN_SUITE) stage 1"
echo "    platform=$PLATFORM"
echo "    architecture=$DEBIAN_ARCH"
echo "    mirror=$DEBIAN_MIRROR"

debootstrap \
  --foreign \
  --arch="$DEBIAN_ARCH" \
  --variant=minbase \
  --exclude=systemd,systemd-sysv \
  --include="$INCLUDE_PACKAGES" \
  "$DEBIAN_SUITE" \
  "$ROOTFS_DIR" \
  "$DEBIAN_MIRROR"

# Prevent package maintainer scripts from attempting to start daemons while the
# rootfs is being configured inside the build chroot.
cat > "$ROOTFS_DIR/usr/sbin/policy-rc.d" <<'POLICY'
#!/bin/sh
exit 101
POLICY
chmod 0755 "$ROOTFS_DIR/usr/sbin/policy-rc.d"

# Provide a real resolver file while package installation is in progress.
# A foreign bootstrap may leave /etc/resolv.conf as a symlink whose target is
# not present yet, so replace it rather than relying on -e.
rm -f "$ROOTFS_DIR/etc/resolv.conf"
cp /etc/resolv.conf "$ROOTFS_DIR/etc/resolv.conf"

echo "==> Completing Debian bootstrap stage 2"
if ! chroot "$ROOTFS_DIR" /debootstrap/debootstrap --second-stage; then
  echo "ERROR: Debian bootstrap stage 2 failed." >&2
  if [[ -f "$ROOTFS_DIR/debootstrap/debootstrap.log" ]]; then
    echo "==> Last 200 lines of debootstrap.log" >&2
    tail -n 200 "$ROOTFS_DIR/debootstrap/debootstrap.log" >&2 || true
  fi
  exit 4
fi

cat > "$ROOTFS_DIR/etc/apt/sources.list" <<EOF_APT
deb $DEBIAN_MIRROR $DEBIAN_SUITE main contrib non-free-firmware
deb $DEBIAN_MIRROR $DEBIAN_SUITE-updates main contrib non-free-firmware
deb https://security.debian.org/debian-security $DEBIAN_SUITE-security main contrib non-free-firmware
EOF_APT

cat > "$ROOTFS_DIR/etc/fstab" <<EOF_FSTAB
# Generated by linux-kirkwood-mvebu-build.
# <file system> <mount point> <type> <options> <dump> <pass>
LABEL=rootfs / $FSTAB_ROOT_TYPE noatime,errors=remount-ro 0 1
tmpfs /tmp tmpfs defaults 0 0
EOF_FSTAB

{
  [[ -z "${NETWORK_RENAME_RULE:-}" ]] || echo "$NETWORK_RENAME_RULE"
  cat <<'EOF_NET'
auto lo eth0
iface lo inet loopback
iface eth0 inet dhcp
EOF_NET
} > "$ROOTFS_DIR/etc/network/interfaces"

printf '%s\n' "$ROOTFS_HOSTNAME" > "$ROOTFS_DIR/etc/hostname"
cat > "$ROOTFS_DIR/etc/hosts" <<EOF_HOSTS
127.0.0.1 localhost
127.0.1.1 $ROOTFS_HOSTNAME

::1 localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
EOF_HOSTS

cat > "$ROOTFS_DIR/etc/linux-kirkwood-mvebu-build-rootfs" <<EOF_MARKER
project=linux-kirkwood-mvebu-build
platform=$PLATFORM
debian_suite=$DEBIAN_SUITE
debian_major=$DEBIAN_MAJOR
debian_arch=$DEBIAN_ARCH
kernel_installed=no
media_installed=no
EOF_MARKER

# Ensure the intended package set and init provider after the second stage.
chroot "$ROOTFS_DIR" /bin/bash -c '
  set -e
  export DEBIAN_FRONTEND=noninteractive
  apt-get update
  apt-get install -y --no-install-recommends \
    sysvinit-core sysvinit-utils sysv-rc orphan-sysvinit-scripts \
    systemd-standalone-sysusers \
    ca-certificates cron e2fsprogs ethtool ifupdown initramfs-tools iproute2 \
    iputils-ping isc-dhcp-client kmod locales logrotate net-tools netbase \
    openssh-server procps rsync rsyslog tzdata u-boot-tools udev wget
  apt-get clean
  rm -rf /var/lib/apt/lists/*
  passwd -l root >/dev/null 2>&1 || true
'

if chroot "$ROOTFS_DIR" dpkg-query -W -f='${Status}\n' systemd-sysv 2>/dev/null | grep -q 'install ok installed'; then
  echo "ERROR: systemd-sysv is still installed; expected sysvinit-core as init." >&2
  exit 5
fi

if ! chroot "$ROOTFS_DIR" dpkg-query -W -f='${Status}\n' sysvinit-core 2>/dev/null | grep -q 'install ok installed'; then
  echo "ERROR: sysvinit-core is not installed." >&2
  exit 5
fi

if ! chroot "$ROOTFS_DIR" dpkg-query -W -f='${Status}\n' systemd-standalone-sysusers 2>/dev/null | grep -q 'install ok installed'; then
  echo "ERROR: systemd-standalone-sysusers is not installed." >&2
  exit 5
fi

# Remove build-only policy and per-build machine identity before packaging.
rm -f "$ROOTFS_DIR/usr/sbin/policy-rc.d"
rm -f "$ROOTFS_DIR"/etc/ssh/ssh_host_*
if [[ -e "$ROOTFS_DIR/etc/machine-id" ]]; then
  : > "$ROOTFS_DIR/etc/machine-id"
fi
rm -f "$ROOTFS_DIR/etc/resolv.conf"
printf '%s\n' '# populated by DHCP on the target system' > "$ROOTFS_DIR/etc/resolv.conf"

chroot "$ROOTFS_DIR" dpkg-query -W -f='${binary:Package}\t${Version}\t${Architecture}\n' \
  | LC_ALL=C sort > "$PACKAGE_MANIFEST"

BUILD_TIME_UTC="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
GIT_SHA="${GITHUB_SHA:-$(git -C "$REPO_ROOT" rev-parse HEAD 2>/dev/null || printf 'not-a-git-checkout')}"
DEBOOTSTRAP_VERSION="$(debootstrap --version 2>/dev/null | head -n 1 || true)"

cat > "$METADATA_FILE" <<EOF_META
project=linux-kirkwood-mvebu-build
platform=$PLATFORM
debian_suite=$DEBIAN_SUITE
debian_major=$DEBIAN_MAJOR
debian_arch=$DEBIAN_ARCH
debian_mirror=$DEBIAN_MIRROR
hostname=$ROOTFS_HOSTNAME
fstab_root_type=$FSTAB_ROOT_TYPE
kernel_installed=no
media_installed=no
build_time_utc=$BUILD_TIME_UTC
git_commit=$GIT_SHA
debootstrap=$DEBOOTSTRAP_VERSION
EOF_META

cp "$METADATA_FILE" "$ROOTFS_DIR/root/ROOTFS-BUILD-METADATA.txt"
cp "$PACKAGE_MANIFEST" "$ROOTFS_DIR/root/ROOTFS-PACKAGE-MANIFEST.txt"

echo "==> Creating rootfs archive"
(
  cd "$ROOTFS_DIR"
  tar --numeric-owner -cjf "$ARCHIVE_PATH" .
)

(
  cd "$OUTPUT_DIR"
  sha256sum "$ARCHIVE_NAME" PACKAGE-MANIFEST.txt ROOTFS-METADATA.txt > SHA256SUMS
)

"$SCRIPT_DIR/validate-generated-rootfs.sh" "$PLATFORM" "$ARCHIVE_PATH"

echo "==> Rootfs build complete"
echo "archive=$ARCHIVE_PATH"
echo "sha256=$(sha256sum "$ARCHIVE_PATH" | awk '{print $1}')"
echo "NOTE: no kernel is installed and no boot media has been created."
